# Generated by Django 4.0.4 on 2022-11-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='bids',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bid'),
        ),
    ]
