# Generated by Django 4.0.4 on 2022-11-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionitem_bids_auctionitem_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bid'),
        ),
    ]
