# Generated by Django 4.0.4 on 2022-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionitem_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListofAuctionItems',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('alist', models.ManyToManyField(blank=True, to='auctions.auctionitem')),
            ],
        ),
    ]
