# Generated by Django 4.0.4 on 2022-11-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listofauctionitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('alist', models.ManyToManyField(blank=True, to='auctions.auctionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ListofAuctionItems',
        ),
    ]
