# Generated by Django 4.0.4 on 2022-11-02 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist_delete_listofauctionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='watching',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
